language: python
python:
  - "2.7"
services:
  - riak
  - redis-server
cache:
  - pip
  - apt
install: make environment
script: make test
notifications:
  irc: "irc.freenode.org#openmining"
  on_success: "never"
